"""
services/razorpay_client.py - Razorpay Payment Gateway Client & Verifier
Implements Phase 8 requirements of INTERNSHIPPORTAL4_LOCAL_AI_AGENT_MASTER_PLAN.md
and docs/PAYMENT_GATEWAY_PLAN.md

Handles:
- Dynamic configuration detection (graceful fallback if keys absent)
- Server-side Razorpay Order creation (canonical price enforcement)
- Cryptographic HMAC-SHA256 signature verification for client checkouts
- Webhook signature validation & idempotency checks
"""

import os
import hmac
import hashlib
import requests
from typing import Optional, Dict, Any, Tuple


class RazorpayError(Exception):
    """Base exception for Razorpay gateway errors."""
    pass


class RazorpayNotConfiguredError(RazorpayError):
    """Raised when an operation requiring Razorpay is attempted without configured credentials."""
    pass


class RazorpayAPIError(RazorpayError):
    """Raised when the Razorpay API returns an error."""
    pass


def get_razorpay_keys() -> Tuple[str, str, str]:
    """Returns (key_id, key_secret, webhook_secret) from environment."""
    key_id = os.environ.get("RAZORPAY_KEY_ID", "").strip()
    key_secret = os.environ.get("RAZORPAY_KEY_SECRET", "").strip()
    webhook_secret = os.environ.get("RAZORPAY_WEBHOOK_SECRET", "").strip()
    return key_id, key_secret, webhook_secret


def is_razorpay_enabled() -> bool:
    """
    Checks if Razorpay is configured and explicitly enabled.
    Returns False when keys are missing or RAZORPAY_ENABLED is 0/false.
    """
    flag = os.environ.get("RAZORPAY_ENABLED", "1").strip().lower()
    if flag in ("0", "false", "no", "off"):
        return False
    key_id, key_secret, _ = get_razorpay_keys()
    return bool(key_id and key_secret)


def get_public_config() -> Dict[str, Any]:
    """Returns safe public config for frontend consumption."""
    enabled = is_razorpay_enabled()
    key_id, _, _ = get_razorpay_keys()
    return {
        "enabled": enabled,
        "key_id": key_id if enabled else "",
        "fallback_available": True
    }


def create_order(
    amount_inr: int,
    receipt: str,
    notes: Optional[Dict[str, Any]] = None,
    currency: str = "INR"
) -> Dict[str, Any]:
    """
    Creates an order on Razorpay using Basic Auth.
    Enforces canonical price: amount_inr is passed as integer INR and converted to paise.
    """
    if not is_razorpay_enabled():
        raise RazorpayNotConfiguredError("Razorpay is not enabled or credentials are missing.")

    key_id, key_secret, _ = get_razorpay_keys()
    amount_paise = int(amount_inr * 100)
    if amount_paise <= 0:
        raise ValueError("Order amount must be greater than 0.")

    url = "https://api.razorpay.com/v1/orders"
    payload = {
        "amount": amount_paise,
        "currency": currency,
        "receipt": receipt[:40],
        "notes": notes or {}
    }

    try:
        resp = requests.post(
            url,
            json=payload,
            auth=(key_id, key_secret),
            timeout=10
        )
    except requests.RequestException as e:
        raise RazorpayAPIError(f"Network error connecting to Razorpay: {e}")

    if resp.status_code != 200 and resp.status_code != 201:
        error_msg = f"Razorpay order creation failed: {resp.status_code} - {resp.text}"
        try:
            err_data = resp.json()
            if "error" in err_data and "description" in err_data["error"]:
                error_msg = err_data["error"]["description"]
        except Exception:
            pass
        raise RazorpayAPIError(error_msg)

    order_data = resp.json()
    return {
        "order_id": order_data["id"],
        "amount": amount_paise,
        "currency": currency,
        "key_id": key_id
    }


def verify_payment_signature(
    razorpay_order_id: str,
    razorpay_payment_id: str,
    razorpay_signature: str
) -> bool:
    """
    Verifies the HMAC-SHA256 signature generated by Razorpay Checkout.js.
    Uses timing-safe comparison to prevent timing side-channel attacks.
    """
    _, key_secret, _ = get_razorpay_keys()
    if not key_secret:
        raise RazorpayNotConfiguredError("Cannot verify signature: RAZORPAY_KEY_SECRET is not configured.")

    if not razorpay_order_id or not razorpay_payment_id or not razorpay_signature:
        return False

    message = f"{razorpay_order_id}|{razorpay_payment_id}".encode("utf-8")
    expected_sig = hmac.new(
        key_secret.encode("utf-8"),
        message,
        hashlib.sha256
    ).hexdigest()

    return hmac.compare_digest(expected_sig, razorpay_signature.strip())


def verify_webhook_signature(
    raw_payload_bytes: bytes,
    webhook_signature: str
) -> bool:
    """
    Verifies that incoming webhook requests genuinely originate from Razorpay.
    """
    _, _, webhook_secret = get_razorpay_keys()
    if not webhook_secret:
        raise RazorpayNotConfiguredError("RAZORPAY_WEBHOOK_SECRET is not configured.")

    if not raw_payload_bytes or not webhook_signature:
        return False

    expected_sig = hmac.new(
        webhook_secret.encode("utf-8"),
        raw_payload_bytes,
        hashlib.sha256
    ).hexdigest()

    return hmac.compare_digest(expected_sig, webhook_signature.strip())
