-- ============================================================================
-- DBERT INTERNSHIP PORTAL 4 — POSTGRESQL STAGING & PRODUCTION SCHEMA
-- Auto-generated by services.database.schema_translator
-- ============================================================================

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------------------
-- TABLES (65 definitions)
-- ----------------------------------------------------------------------------

-- Table: abuse_log
CREATE TABLE IF NOT EXISTS abuse_log (
    id SERIAL PRIMARY KEY,
    timestamp TEXT NOT NULL,
    ip TEXT,
    route TEXT,
    bucket TEXT,
    reason TEXT,
    email TEXT
);

-- Table: ambassador_withdrawals
CREATE TABLE IF NOT EXISTS ambassador_withdrawals (
    id                   SERIAL PRIMARY KEY,
    intern_id            INTEGER NOT NULL,
    amount               INTEGER NOT NULL,
    status               TEXT DEFAULT 'pending',
    -- pending|approved|paid|rejected
                requested_at         TEXT DEFAULT CURRENT_TIMESTAMP,
    reviewed_by_admin_id INTEGER,
    reviewed_at          TEXT,
    admin_note           TEXT,
    upi_viewed_by        TEXT,
    -- §6.5 audit: who decrypted the UPI
                upi_viewed_at        TEXT
);

-- Table: application_status_history
CREATE TABLE IF NOT EXISTS application_status_history (
    id SERIAL PRIMARY KEY,
    application_id INTEGER NOT NULL,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by TEXT,
    changed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    reason TEXT,
    request_id TEXT,
    metadata TEXT
);

-- Table: applications
CREATE TABLE IF NOT EXISTS applications (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    city TEXT NOT NULL,
    college TEXT NOT NULL,
    course TEXT NOT NULL,
    semester TEXT NOT NULL,
    year_of_passing TEXT NOT NULL,
    domain TEXT NOT NULL,
    why_join TEXT NOT NULL,
    portfolio TEXT,
    status TEXT DEFAULT 'Apply Pending',
    mentor_note TEXT,
    mentor_email TEXT,
    reviewed_at TEXT,
    visitor_id TEXT,
    source TEXT DEFAULT 'web',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    rejected_at TEXT,
    enroll_reminders_sent INTEGER DEFAULT 0,
    last_reminder_at TEXT,
    intent_answers TEXT,
    UNIQUE(email, domain)
);

-- Table: attendance
CREATE TABLE IF NOT EXISTS attendance (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    week_start TEXT NOT NULL,
    week_end   TEXT NOT NULL,
    total_minutes INTEGER DEFAULT 0,
    updated_at TEXT,
    email TEXT,
    UNIQUE(intern_id, week_start),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: check_log
CREATE TABLE IF NOT EXISTS check_log (
    id SERIAL PRIMARY KEY,
    timestamp TEXT NOT NULL,
    email TEXT NOT NULL,
    name TEXT,
    check_count INTEGER,
    ip TEXT
);

-- Table: cohort_enrollments
CREATE TABLE IF NOT EXISTS cohort_enrollments (
    id            SERIAL PRIMARY KEY,
    cohort_id     INTEGER NOT NULL,
    intern_id     INTEGER NOT NULL,
    reminder_sent INTEGER DEFAULT 0,
    created_at    TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(cohort_id, intern_id),
    FOREIGN KEY(cohort_id) REFERENCES cohorts(id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: cohorts
CREATE TABLE IF NOT EXISTS cohorts (
    id          SERIAL PRIMARY KEY,
    company_id  INTEGER NOT NULL,
    title       TEXT NOT NULL,
    description TEXT,
    skills      TEXT,
    platform    TEXT,
    -- 'Zoom'|'Discord'|...
                meeting_url TEXT,
    -- revealed to enrollees only
                starts_at   TEXT,
    -- 'YYYY-MM-DD HH:MM' (IST)
                capacity    INTEGER DEFAULT 0,
    -- 0 = unlimited
                status      TEXT DEFAULT 'pending',
    -- pending|published|rejected
                created_at  TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at  TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(company_id) REFERENCES companies(id)
);

-- Table: coin_ledger_mirror
CREATE TABLE IF NOT EXISTS coin_ledger_mirror (
    id            SERIAL PRIMARY KEY,
    intern_id     INTEGER NOT NULL,
    ledger_kind   TEXT NOT NULL,
    -- 'ad' | 'task'
                delta         INTEGER NOT NULL,
    balance_after INTEGER,
    reason        TEXT,
    event_ts      TEXT,
    received_at   TEXT DEFAULT CURRENT_TIMESTAMP,
    idem_key      TEXT UNIQUE,
    email TEXT
);

-- Table: companies
CREATE TABLE IF NOT EXISTS companies (
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    phone         TEXT,
    website       TEXT,
    about         TEXT,
    password_hash TEXT,
    is_approved   INTEGER DEFAULT 0,
    is_active     INTEGER DEFAULT 1,
    created_at    TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at    TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: company_follows
CREATE TABLE IF NOT EXISTS company_follows (
    id         SERIAL PRIMARY KEY,
    intern_id  INTEGER NOT NULL,
    company_id INTEGER NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(intern_id, company_id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id),
    FOREIGN KEY(company_id) REFERENCES companies(id)
);

-- Table: conversations
CREATE TABLE IF NOT EXISTS conversations (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    counterparty_type TEXT NOT NULL,
    -- 'mentor'|'admin'|'company'
                counterparty_id INTEGER NOT NULL,
    post_id INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(intern_id, counterparty_type, counterparty_id, post_id)
);

-- Table: course_chapters
CREATE TABLE IF NOT EXISTS course_chapters (
    id SERIAL PRIMARY KEY,
    course_id INTEGER NOT NULL,
    day_number INTEGER NOT NULL,
    title TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(course_id) REFERENCES courses(id)
);

-- Table: course_day_quizzes
CREATE TABLE IF NOT EXISTS course_day_quizzes (
    id SERIAL PRIMARY KEY,
    course_id INTEGER NOT NULL,
    day_number INTEGER NOT NULL,
    questions_json TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(course_id, day_number),
    FOREIGN KEY(course_id) REFERENCES courses(id)
);

-- Table: course_enrollments
CREATE TABLE IF NOT EXISTS course_enrollments (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at TEXT DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    current_day INTEGER DEFAULT 1,
    completed_at TEXT,
    email TEXT,
    UNIQUE(intern_id, course_id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id),
    FOREIGN KEY(course_id) REFERENCES courses(id)
);

-- Table: course_payments
CREATE TABLE IF NOT EXISTS course_payments (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    course_title TEXT,
    amount INTEGER,
    payment_screenshot TEXT,
    status TEXT DEFAULT 'pending',
    -- pending|verified|rejected
                admin_note TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    platform_commission_pct REAL DEFAULT 15.0,
    author_earnings_inr INTEGER DEFAULT 0,
    commission_pct_snapshot REAL DEFAULT 0.0,
    commission_amount REAL DEFAULT 0.0,
    payee_type TEXT DEFAULT 'admin',
    settled_at TEXT,
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    razorpay_signature TEXT
);

-- Table: course_projects
CREATE TABLE IF NOT EXISTS course_projects (
    id SERIAL PRIMARY KEY,
    course_id INTEGER NOT NULL UNIQUE,
    brief TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(course_id) REFERENCES courses(id)
);

-- Table: course_subtopic_chats
CREATE TABLE IF NOT EXISTS course_subtopic_chats (
    id SERIAL PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    subtopic_id INTEGER NOT NULL,
    role TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(enrollment_id) REFERENCES course_enrollments(id),
    FOREIGN KEY(subtopic_id) REFERENCES course_subtopics(id)
);

-- Table: course_subtopics
CREATE TABLE IF NOT EXISTS course_subtopics (
    id SERIAL PRIMARY KEY,
    chapter_id INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    title TEXT NOT NULL,
    brief TEXT NOT NULL,
    key_takeaways_json TEXT,
    prompt_seed TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(chapter_id) REFERENCES course_chapters(id)
);

-- Table: courses
CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT,
    domain TEXT,
    company_id INTEGER,
    -- NULL = DBERT/admin course
                is_paid INTEGER DEFAULT 0,
    price_inr INTEGER DEFAULT 0,
    content_status TEXT DEFAULT 'pending',
    -- pending|approved|rejected (DBERT review before co-sign)
                source TEXT DEFAULT 'custom',
    -- 'custom' | 'tutor'
                is_active INTEGER DEFAULT 1,
    payout_note TEXT,
    -- back-office: remittance to company (DBERT collects)
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    level TEXT DEFAULT 'Beginner',
    estimated_hours INTEGER DEFAULT 10,
    author_type TEXT DEFAULT 'admin',
    author_id INTEGER,
    requires_project INTEGER DEFAULT 0,
    program TEXT DEFAULT 'fellowship',
    banner_gradient TEXT DEFAULT 'linear-gradient(135deg, #8B5CF6, #3B82F6)',
    updated_at TEXT DEFAULT ''
);

-- Table: cvs
CREATE TABLE IF NOT EXISTS cvs (
    id              SERIAL PRIMARY KEY,
    intern_id       INTEGER NOT NULL UNIQUE,
    slug            TEXT UNIQUE,
    headline        TEXT,
    summary         TEXT,
    skills_json     TEXT,
    projects_json   TEXT,
    experience_json TEXT,
    education_json  TEXT,
    links_json      TEXT,
    is_public       INTEGER DEFAULT 1,
    updated_at      TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: day_quiz_attempts
CREATE TABLE IF NOT EXISTS day_quiz_attempts (
    id SERIAL PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    day_quiz_id INTEGER NOT NULL,
    score INTEGER NOT NULL,
    max_score INTEGER NOT NULL,
    passed INTEGER NOT NULL,
    tab_switches INTEGER DEFAULT 0,
    time_taken_sec INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(enrollment_id) REFERENCES course_enrollments(id),
    FOREIGN KEY(day_quiz_id) REFERENCES course_day_quizzes(id)
);

-- Table: dbert_fallback_usage
CREATE TABLE IF NOT EXISTS dbert_fallback_usage (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    usage_date TEXT NOT NULL,
    count INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(intern_id, usage_date),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: device_profiles
CREATE TABLE IF NOT EXISTS device_profiles (
    id SERIAL PRIMARY KEY,
    visitor_id TEXT,
    email TEXT,
    ip_address TEXT,
    user_agent TEXT,
    screen_res TEXT,
    timezone TEXT,
    language TEXT,
    device_type TEXT,
    referrer TEXT,
    is_return_visit INTEGER DEFAULT 0,
    visit_count INTEGER DEFAULT 1,
    time_on_page INTEGER DEFAULT 0,
    intent_score INTEGER DEFAULT 0,
    path TEXT,
    last_seen TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: email_log
CREATE TABLE IF NOT EXISTS email_log (
    id SERIAL PRIMARY KEY,
    timestamp TEXT NOT NULL,
    email TEXT NOT NULL,
    name TEXT,
    subject TEXT,
    email_sent TEXT DEFAULT 'YES',
    opened_at TEXT
);

-- Table: enrollment_status_history
CREATE TABLE IF NOT EXISTS enrollment_status_history (
    id SERIAL PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by TEXT,
    changed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    reason TEXT,
    request_id TEXT,
    metadata TEXT
);

-- Table: enrollments
CREATE TABLE IF NOT EXISTS enrollments (
    id SERIAL PRIMARY KEY,
    application_id INTEGER,
    timestamp TEXT,
    name TEXT,
    email TEXT,
    phone TEXT,
    city TEXT,
    college TEXT,
    course TEXT,
    semester TEXT,
    year_of_passing TEXT,
    domain TEXT,
    joining_date TEXT,
    batch_label TEXT,
    payment_screenshot TEXT,
    payment_status TEXT,
    admin_note TEXT,
    created_at TEXT,
    updated_at TEXT,
    product TEXT DEFAULT 'free_deposit',
    amount INTEGER,
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    razorpay_signature TEXT
);

-- Table: event_outbox
CREATE TABLE IF NOT EXISTS event_outbox (
    id SERIAL PRIMARY KEY,
    event_type TEXT NOT NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 3,
    next_retry_at TEXT,
    last_error TEXT,
    processed_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: gl_concepts
CREATE TABLE IF NOT EXISTS gl_concepts (
    concept_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    domain TEXT NOT NULL,
    subject TEXT NOT NULL,
    module_id INTEGER,
    subtopic_id INTEGER,
    difficulty INTEGER DEFAULT 1,
    prerequisites_json TEXT DEFAULT '[]',
    learning_objectives_json TEXT DEFAULT '[]',
    assessment_criteria_json TEXT DEFAULT '[]',
    common_misconceptions_json TEXT DEFAULT '[]',
    resources_json TEXT DEFAULT '[]',
    created_at TEXT NOT NULL
);

-- Table: gl_learning_events
CREATE TABLE IF NOT EXISTS gl_learning_events (
    id SERIAL PRIMARY KEY,
    event_uuid TEXT UNIQUE NOT NULL,
    student_id INTEGER NOT NULL,
    concept_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Table: gl_learning_sessions
CREATE TABLE IF NOT EXISTS gl_learning_sessions (
    session_id TEXT PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    subtopic_id INTEGER,
    current_concept_id TEXT,
    current_action TEXT DEFAULT 'EXPLAIN',
    action_state_json TEXT DEFAULT '{}',
    idempotency_key TEXT,
    status TEXT DEFAULT 'active',
    last_heartbeat_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Table: gl_misconception_catalog
CREATE TABLE IF NOT EXISTS gl_misconception_catalog (
    misconception_id TEXT PRIMARY KEY,
    concept_id TEXT NOT NULL,
    label TEXT NOT NULL,
    pattern_description TEXT NOT NULL,
    remediation_strategy TEXT NOT NULL,
    example_trigger TEXT,
    FOREIGN KEY (concept_id) REFERENCES gl_concepts(concept_id) ON DELETE CASCADE
);

-- Table: gl_student_mastery
CREATE TABLE IF NOT EXISTS gl_student_mastery (
    student_id INTEGER NOT NULL,
    concept_id TEXT NOT NULL,
    mastery_score REAL DEFAULT 0.0,
    mastery_level TEXT DEFAULT 'NOVICE',
    confidence REAL DEFAULT 0.0,
    learning_velocity REAL DEFAULT 1.0,
    total_attempts INTEGER DEFAULT 0,
    successful_attempts INTEGER DEFAULT 0,
    consecutive_successes INTEGER DEFAULT 0,
    misconceptions_json TEXT DEFAULT '[]',
    last_evidence_json TEXT DEFAULT '{}',
    last_interaction_at TEXT,
    last_review_at TEXT,
    next_review_at TEXT,
    review_interval_days REAL DEFAULT 1.0,
    review_count INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (student_id, concept_id),
    FOREIGN KEY (concept_id) REFERENCES gl_concepts(concept_id) ON DELETE CASCADE
);

-- Table: intern_accounts
CREATE TABLE IF NOT EXISTS intern_accounts (
    id SERIAL PRIMARY KEY,
    application_id INTEGER,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    city TEXT,
    college TEXT,
    course TEXT,
    semester TEXT,
    year_of_passing TEXT,
    domain TEXT,
    password_hash TEXT,
    password_set INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    tutor_completion_pct REAL DEFAULT 0.0,
    tutor_updated_at TEXT,
    tutor_seconds_credited INTEGER DEFAULT 0,
    tutor_week_credited TEXT DEFAULT '',
    linkedin_url TEXT,
    github_url TEXT,
    interview_attempts INTEGER DEFAULT 0,
    interview_last_attempt_at TEXT,
    interview_locked INTEGER DEFAULT 0,
    terms_accepted_at TEXT,
    newsletter_opt_in INTEGER DEFAULT 0,
    signup_stage INTEGER DEFAULT 3,
    referral_code TEXT,
    referred_by_intern_id INTEGER,
    upi_id_encrypted TEXT,
    email_verified INTEGER DEFAULT 0,
    account_status TEXT,
    program TEXT DEFAULT 'fellowship',
    visitor_id TEXT DEFAULT NULL,
    FOREIGN KEY(application_id) REFERENCES applications(id)
);

-- Table: intern_certificates
CREATE TABLE IF NOT EXISTS intern_certificates (
    id           SERIAL PRIMARY KEY,
    intern_id    INTEGER NOT NULL,
    course_id    INTEGER,
    course_title TEXT,
    cert_id      TEXT,
    issued_at    TEXT,
    url          TEXT,
    received_at  TEXT DEFAULT CURRENT_TIMESTAMP,
    tier TEXT DEFAULT 'completed',
    email TEXT,
    UNIQUE(intern_id, cert_id)
);

-- Table: interviews
CREATE TABLE IF NOT EXISTS interviews (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    application_id INTEGER,
    domain TEXT,
    attempt_no INTEGER DEFAULT 1,
    status TEXT DEFAULT 'not_started',
    questions_json TEXT,
    answers_json TEXT,
    mentor_assessment_json TEXT,
    candidate_focus_json TEXT,
    github_summary TEXT,
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    post_id INTEGER,
    time_taken_sec INTEGER DEFAULT 0,
    tab_switches INTEGER DEFAULT 0
);

-- Table: mentor_availability_slots
CREATE TABLE IF NOT EXISTS mentor_availability_slots (
    id SERIAL PRIMARY KEY,
    mentor_staff_id INTEGER NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    is_booked INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(mentor_staff_id) REFERENCES staff_accounts(id)
);

-- Table: mentor_session_bookings
CREATE TABLE IF NOT EXISTS mentor_session_bookings (
    id SERIAL PRIMARY KEY,
    slot_id INTEGER NOT NULL UNIQUE,
    intern_id INTEGER NOT NULL,
    meeting_link TEXT,
    status TEXT DEFAULT 'booked',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(slot_id) REFERENCES mentor_availability_slots(id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: mentors
CREATE TABLE IF NOT EXISTS mentors (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    domain TEXT NOT NULL,
    password_hash TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: messages
CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    conversation_id INTEGER NOT NULL,
    sender_type TEXT NOT NULL,
    -- 'intern'|'mentor'|'admin'|'company'
                sender_id INTEGER NOT NULL,
    body TEXT NOT NULL,
    is_read INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(conversation_id) REFERENCES conversations(id)
);

-- Table: mobile_refresh_tokens
CREATE TABLE IF NOT EXISTS mobile_refresh_tokens (
    id SERIAL PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    -- HASH of the refresh token,
    never plaintext
                intern_id  TEXT NOT NULL,
    -- str(intern_accounts.id)
                email      TEXT NOT NULL,
    issued_at  TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked    INTEGER NOT NULL DEFAULT 0,
    last_used_at TEXT
);

-- Table: notifications
CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    kind TEXT DEFAULT 'general',
    title TEXT NOT NULL,
    body TEXT,
    link TEXT,
    is_read INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: password_resets
CREATE TABLE IF NOT EXISTS password_resets (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    token TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    account_type TEXT NOT NULL DEFAULT 'intern',
    account_id INTEGER,
    used_at TEXT
);

-- Table: payment_events
CREATE TABLE IF NOT EXISTS payment_events (
    id SERIAL PRIMARY KEY,
    event_id TEXT UNIQUE NOT NULL,
    event_type TEXT NOT NULL,
    payload TEXT,
    processed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    status TEXT DEFAULT 'processed'
);

-- Table: payments
CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY,
    mentor_email TEXT NOT NULL,
    intern_name TEXT,
    course_title TEXT,
    amount INTEGER,
    verified INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: platform_config
CREATE TABLE IF NOT EXISTS platform_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: post_applications
CREATE TABLE IF NOT EXISTS post_applications (
    id         SERIAL PRIMARY KEY,
    post_id    INTEGER NOT NULL,
    intern_id  INTEGER NOT NULL,
    comment    TEXT NOT NULL,
    cv_id      INTEGER,
    status     TEXT DEFAULT 'Applied',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    needed_certs_json TEXT,
    decision_note TEXT,
    decided_at TEXT,
    notified_at TEXT,
    email TEXT,
    UNIQUE(post_id, intern_id),
    FOREIGN KEY(post_id) REFERENCES posts(id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: post_comments
CREATE TABLE IF NOT EXISTS post_comments (
    id SERIAL PRIMARY KEY,
    post_id INTEGER NOT NULL,
    intern_id INTEGER NOT NULL,
    body TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(post_id) REFERENCES posts(id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: post_hire_deposits
CREATE TABLE IF NOT EXISTS post_hire_deposits (
    id SERIAL PRIMARY KEY,
    post_application_id INTEGER NOT NULL,
    intern_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    amount INTEGER,
    payment_screenshot TEXT,
    status TEXT DEFAULT 'pending',
    -- pending|verified|rejected|refunded
                admin_note TEXT,
    refunded_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    razorpay_signature TEXT
);

-- Table: post_questions
CREATE TABLE IF NOT EXISTS post_questions (
    id SERIAL PRIMARY KEY,
    post_id INTEGER NOT NULL,
    company_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending',
    -- pending|approved|rejected
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    options TEXT DEFAULT '[]',
    FOREIGN KEY(post_id) REFERENCES posts(id)
);

-- Table: posts
CREATE TABLE IF NOT EXISTS posts (
    id                 SERIAL PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    post_type          TEXT NOT NULL,
    domain             TEXT NOT NULL,
    title              TEXT NOT NULL,
    slug               TEXT,
    description        TEXT,
    responsibilities   TEXT,
    skills             TEXT,
    location           TEXT,
    work_mode          TEXT,
    stipend_min        INTEGER,
    stipend_max        INTEGER,
    pay_period         TEXT,
    is_unpaid          INTEGER DEFAULT 0,
    duration           TEXT,
    openings           INTEGER DEFAULT 1,
    apply_by           TEXT,
    certifications_json TEXT,
    eligibility        TEXT,
    status             TEXT DEFAULT 'draft',
    published_at       TEXT,
    expires_at         TEXT,
    views              INTEGER DEFAULT 0,
    created_at         TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(company_id) REFERENCES companies(id)
);

-- Table: project_submissions
CREATE TABLE IF NOT EXISTS project_submissions (
    id SERIAL PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    intern_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    github_repo_url TEXT NOT NULL,
    project_title TEXT NOT NULL,
    project_description TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    reviewed_by_staff_id INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(enrollment_id) REFERENCES course_enrollments(id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id),
    FOREIGN KEY(course_id) REFERENCES courses(id),
    FOREIGN KEY(reviewed_by_staff_id) REFERENCES staff_accounts(id)
);

-- Table: rate_events
CREATE TABLE IF NOT EXISTS rate_events (
    id SERIAL PRIMARY KEY,
    bucket TEXT NOT NULL,
    created_at REAL NOT NULL
);

-- Table: referrals
CREATE TABLE IF NOT EXISTS referrals (
    id                 SERIAL PRIMARY KEY,
    referrer_intern_id INTEGER NOT NULL,
    referred_email     TEXT,
    referred_intern_id INTEGER,
    -- filled when they sign up
                source_code        TEXT,
    status             TEXT DEFAULT 'clicked',
    -- clicked|signed_up|converted
                flagged            INTEGER DEFAULT 0,
    -- §6.4 device-overlap flag
                flag_reason        TEXT,
    created_at         TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT
);

-- Table: review_log
CREATE TABLE IF NOT EXISTS review_log (
    id SERIAL PRIMARY KEY,
    queue_name TEXT NOT NULL,
    staff_id INTEGER NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id INTEGER NOT NULL,
    decision TEXT NOT NULL,
    reason_code TEXT,
    reviewed_input_snapshot TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(staff_id) REFERENCES staff_accounts(id)
);

-- Table: security_deposits
CREATE TABLE IF NOT EXISTS security_deposits (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    amount INTEGER DEFAULT 499,
    payment_screenshot TEXT,
    status TEXT DEFAULT 'pending',
    payment_type TEXT DEFAULT 'pending',
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    razorpay_signature TEXT,
    admin_note TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT
);

-- Table: signup_otps
CREATE TABLE IF NOT EXISTS signup_otps (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    otp TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    is_used INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Table: staff_accounts
CREATE TABLE IF NOT EXISTS staff_accounts (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    role TEXT DEFAULT "admin"
);

-- Table: staff_queue_roles
CREATE TABLE IF NOT EXISTS staff_queue_roles (
    id SERIAL PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    queue_name TEXT NOT NULL,
    UNIQUE(staff_id, queue_name),
    FOREIGN KEY(staff_id) REFERENCES staff_accounts(id)
);

-- Table: task_submissions
CREATE TABLE IF NOT EXISTS task_submissions (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    task_id INTEGER NOT NULL,
    task_version_id INTEGER NOT NULL,
    submission_content TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    coins_awarded INTEGER DEFAULT 0,
    reviewed_by_staff_id INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    submission_file TEXT DEFAULT '',
    email TEXT,
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id),
    FOREIGN KEY(task_id) REFERENCES tasks(id),
    FOREIGN KEY(task_version_id) REFERENCES task_versions(id),
    FOREIGN KEY(reviewed_by_staff_id) REFERENCES staff_accounts(id)
);

-- Table: task_versions
CREATE TABLE IF NOT EXISTS task_versions (
    id SERIAL PRIMARY KEY,
    task_id INTEGER NOT NULL,
    version_number INTEGER NOT NULL,
    instructions TEXT NOT NULL,
    rubric TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(task_id, version_number),
    FOREIGN KEY(task_id) REFERENCES tasks(id)
);

-- Table: tasks
CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    coin_reward INTEGER NOT NULL DEFAULT 10,
    is_active INTEGER DEFAULT 1,
    author_type TEXT DEFAULT 'admin',
    author_id INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    task_type TEXT DEFAULT 'general',
    target_domain TEXT DEFAULT '',
    payment_type TEXT DEFAULT 'paid',
    submission_type TEXT DEFAULT 'url'
);

-- Table: tutor_progress
CREATE TABLE IF NOT EXISTS tutor_progress (
    id              SERIAL PRIMARY KEY,
    intern_id       INTEGER NOT NULL,
    lessons_json    TEXT    DEFAULT '[]',
    quizzes_json    TEXT    DEFAULT '[]',
    projects_json   TEXT    DEFAULT '[]',
    completion_pct  REAL    DEFAULT 0.0,
    total_lessons   INTEGER DEFAULT 0,
    done_lessons    INTEGER DEFAULT 0,
    updated_at      TEXT,
    UNIQUE(intern_id),
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: user_api_keys
CREATE TABLE IF NOT EXISTS user_api_keys (
    id SERIAL PRIMARY KEY,
    intern_id INTEGER NOT NULL,
    encrypted_key TEXT NOT NULL,
    key_hash TEXT UNIQUE,
    validated_at TEXT,
    available_models_json TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(intern_id) REFERENCES intern_accounts(id)
);

-- Table: user_sessions
CREATE TABLE IF NOT EXISTS user_sessions (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT DEFAULT 'intern',
    session_token TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    next_url TEXT
);

-- ----------------------------------------------------------------------------
-- INDEXES (79 definitions)
-- ----------------------------------------------------------------------------

-- Index: idx_abuse_time
CREATE INDEX idx_abuse_time ON abuse_log(id DESC);

-- Index: idx_app_status_hist_app
CREATE INDEX idx_app_status_hist_app ON application_status_history(application_id);

-- Index: idx_applications_email
CREATE INDEX idx_applications_email ON applications(email);

-- Index: idx_applications_status_created
CREATE INDEX idx_applications_status_created ON applications(status, created_at DESC);

-- Index: idx_attendance_intern_week
CREATE INDEX idx_attendance_intern_week ON attendance(intern_id, week_start DESC);

-- Index: idx_chapters_course
CREATE INDEX idx_chapters_course ON course_chapters(course_id, day_number);

-- Index: idx_chats_subtopic
CREATE INDEX idx_chats_subtopic ON course_subtopic_chats(enrollment_id, subtopic_id);

-- Index: idx_cohort_enr
CREATE INDEX idx_cohort_enr ON cohort_enrollments(cohort_id, intern_id);

-- Index: idx_cohorts_company
CREATE INDEX idx_cohorts_company ON cohorts(company_id, status);

-- Index: idx_cohorts_live
CREATE INDEX idx_cohorts_live ON cohorts(status, starts_at);

-- Index: idx_coin_mirror_intern
CREATE INDEX idx_coin_mirror_intern ON coin_ledger_mirror(intern_id, event_ts);

-- Index: idx_coin_mirror_kind
CREATE INDEX idx_coin_mirror_kind ON coin_ledger_mirror(intern_id, ledger_kind);

-- Index: idx_companies_email
CREATE INDEX idx_companies_email ON companies(email);

-- Index: idx_conv_cp
CREATE INDEX idx_conv_cp ON conversations(counterparty_type, counterparty_id, updated_at);

-- Index: idx_conv_intern
CREATE INDEX idx_conv_intern ON conversations(intern_id, updated_at);

-- Index: idx_course_day_quizzes_course
CREATE INDEX idx_course_day_quizzes_course ON course_day_quizzes(course_id, day_number);

-- Index: idx_course_enr_email
CREATE INDEX idx_course_enr_email ON course_enrollments(email);

-- Index: idx_course_enr_intern
CREATE INDEX idx_course_enr_intern ON course_enrollments(intern_id);

-- Index: idx_course_pay_active
CREATE UNIQUE INDEX idx_course_pay_active
                ON course_payments(intern_id, course_id) WHERE status IN ('pending','verified');

-- Index: idx_courses_status
CREATE INDEX idx_courses_status ON courses(content_status, is_active);

-- Index: idx_cvs_slug
CREATE INDEX idx_cvs_slug ON cvs(slug);

-- Index: idx_device_visitor
CREATE UNIQUE INDEX idx_device_visitor ON device_profiles(visitor_id);

-- Index: idx_enr_status_hist_enr
CREATE INDEX idx_enr_status_hist_enr ON enrollment_status_history(enrollment_id);

-- Index: idx_enrollments_email
CREATE INDEX idx_enrollments_email ON enrollments(email);

-- Index: idx_enrollments_status_created
CREATE INDEX idx_enrollments_status_created ON enrollments(payment_status, created_at DESC);

-- Index: idx_fallback_usage
CREATE INDEX idx_fallback_usage ON dbert_fallback_usage(intern_id, usage_date);

-- Index: idx_follows_company
CREATE INDEX idx_follows_company ON company_follows(company_id);

-- Index: idx_follows_intern
CREATE INDEX idx_follows_intern ON company_follows(intern_id);

-- Index: idx_gl_concepts_domain
CREATE INDEX idx_gl_concepts_domain ON gl_concepts(domain);

-- Index: idx_gl_concepts_subtopic
CREATE INDEX idx_gl_concepts_subtopic ON gl_concepts(subtopic_id);

-- Index: idx_gl_events_concept
CREATE INDEX idx_gl_events_concept ON gl_learning_events(concept_id);

-- Index: idx_gl_events_session
CREATE INDEX idx_gl_events_session ON gl_learning_events(session_id);

-- Index: idx_gl_events_student
CREATE INDEX idx_gl_events_student ON gl_learning_events(student_id);

-- Index: idx_gl_events_type
CREATE INDEX idx_gl_events_type ON gl_learning_events(event_type);

-- Index: idx_gl_mastery_level
CREATE INDEX idx_gl_mastery_level ON gl_student_mastery(student_id, mastery_level);

-- Index: idx_gl_mastery_review
CREATE INDEX idx_gl_mastery_review ON gl_student_mastery(student_id, next_review_at);

-- Index: idx_gl_mastery_student
CREATE INDEX idx_gl_mastery_student ON gl_student_mastery(student_id);

-- Index: idx_gl_misconception_concept
CREATE INDEX idx_gl_misconception_concept ON gl_misconception_catalog(concept_id);

-- Index: idx_gl_sessions_course
CREATE INDEX idx_gl_sessions_course ON gl_learning_sessions(student_id, course_id);

-- Index: idx_gl_sessions_student
CREATE INDEX idx_gl_sessions_student ON gl_learning_sessions(student_id, status);

-- Index: idx_intern_certs_intern
CREATE INDEX idx_intern_certs_intern ON intern_certificates(intern_id);

-- Index: idx_intern_referral_code
CREATE UNIQUE INDEX idx_intern_referral_code ON intern_accounts(referral_code) WHERE referral_code IS NOT NULL;

-- Index: idx_interviews_email
CREATE INDEX idx_interviews_email ON interviews(email);

-- Index: idx_mentor_bookings
CREATE INDEX idx_mentor_bookings ON mentor_session_bookings(intern_id, status);

-- Index: idx_mentor_slots
CREATE INDEX idx_mentor_slots ON mentor_availability_slots(mentor_staff_id, is_booked, start_time);

-- Index: idx_mobile_refresh_hash
CREATE INDEX idx_mobile_refresh_hash   ON mobile_refresh_tokens(token_hash);

-- Index: idx_mobile_refresh_intern
CREATE INDEX idx_mobile_refresh_intern ON mobile_refresh_tokens(intern_id);

-- Index: idx_msg_conv
CREATE INDEX idx_msg_conv ON messages(conversation_id, id);

-- Index: idx_notif_intern
CREATE INDEX idx_notif_intern ON notifications(intern_id, is_read, created_at);

-- Index: idx_outbox_aggregate
CREATE INDEX idx_outbox_aggregate ON event_outbox(aggregate_type, aggregate_id);

-- Index: idx_outbox_status_retry
CREATE INDEX idx_outbox_status_retry ON event_outbox(status, next_retry_at);

-- Index: idx_payment_events_eid
CREATE INDEX idx_payment_events_eid ON payment_events(event_id);

-- Index: idx_post_hire_deposit_active
CREATE UNIQUE INDEX idx_post_hire_deposit_active
                ON post_hire_deposits(post_application_id) WHERE status IN ('pending','verified');

-- Index: idx_postapps_intern
CREATE INDEX idx_postapps_intern ON post_applications(intern_id);

-- Index: idx_postapps_post
CREATE INDEX idx_postapps_post ON post_applications(post_id, id);

-- Index: idx_postcomments_post
CREATE INDEX idx_postcomments_post ON post_comments(post_id, id);

-- Index: idx_postq_post
CREATE INDEX idx_postq_post ON post_questions(post_id, sort_order);

-- Index: idx_posts_company
CREATE INDEX idx_posts_company ON posts(company_id, status);

-- Index: idx_posts_expires
CREATE INDEX idx_posts_expires ON posts(expires_at);

-- Index: idx_posts_live
CREATE INDEX idx_posts_live ON posts(post_type, status, domain);

-- Index: idx_project_sub_intern
CREATE INDEX idx_project_sub_intern ON project_submissions(intern_id, course_id);

-- Index: idx_project_sub_status
CREATE INDEX idx_project_sub_status ON project_submissions(status, created_at);

-- Index: idx_quiz_attempts_enr
CREATE INDEX idx_quiz_attempts_enr ON day_quiz_attempts(enrollment_id, day_quiz_id);

-- Index: idx_rate_bucket_time
CREATE INDEX idx_rate_bucket_time ON rate_events(bucket, created_at);

-- Index: idx_referrals_referred
CREATE INDEX idx_referrals_referred ON referrals(referred_intern_id);

-- Index: idx_referrals_referrer
CREATE INDEX idx_referrals_referrer ON referrals(referrer_intern_id, status);

-- Index: idx_referrals_unique_referred
CREATE UNIQUE INDEX idx_referrals_unique_referred
                ON referrals(referred_intern_id) WHERE referred_intern_id IS NOT NULL;

-- Index: idx_review_queue
CREATE INDEX idx_review_queue ON review_log(queue_name, created_at);

-- Index: idx_review_subject
CREATE INDEX idx_review_subject ON review_log(subject_type, subject_id);

-- Index: idx_signup_otps
CREATE INDEX idx_signup_otps ON signup_otps(email, is_used, expires_at);

-- Index: idx_staff_email
CREATE INDEX idx_staff_email ON staff_accounts(email);

-- Index: idx_staff_roles
CREATE INDEX idx_staff_roles ON staff_queue_roles(staff_id, queue_name);

-- Index: idx_subtopics_chapter
CREATE INDEX idx_subtopics_chapter ON course_subtopics(chapter_id, sort_order);

-- Index: idx_task_sub_intern
CREATE INDEX idx_task_sub_intern ON task_submissions(intern_id, task_id);

-- Index: idx_task_sub_status
CREATE INDEX idx_task_sub_status ON task_submissions(status, created_at);

-- Index: idx_task_ver
CREATE INDEX idx_task_ver ON task_versions(task_id, version_number);

-- Index: idx_tasks_active
CREATE INDEX idx_tasks_active ON tasks(is_active, created_at);

-- Index: idx_user_keys_intern
CREATE INDEX idx_user_keys_intern ON user_api_keys(intern_id);

-- Index: idx_withdrawals_intern
CREATE INDEX idx_withdrawals_intern ON ambassador_withdrawals(intern_id, status);
